  version: 1

  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO # log info messages and higher to the console
      stream: ext://sys.stdout
      formatter: simple # use the formatter 'simple'
    debug_file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      maxBytes: 10485760 # Max file size is 10 MB
      backupCount: 20 # Number of files to rotate
      filename: debug_log_file.txt
      formatter: simple # use the formatter 'simple'

  root:
    level: NOTSET # the log level is set in the handler instead
    handlers: [console, debug_file]